version: '3.9'
services:
  postgres:
    image: postgres:14
    restart: always
    volumes:
      - ${HOST_DATA_DIR}:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  graphql-engine:
    image: hasura/graphql-engine:v2.25.0
    ports:
      - "${HASURA_PORT}:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:password@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: ${HASURA_GRAPHQL_ENABLE_CONSOLE}
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      # https://hasura.io/docs/latest/graphql/core/auth/authentication/jwt.html
      HASURA_GRAPHQL_JWT_SECRET: ${HASURA_GRAPHQL_JWT_SECRET}

  nginx:
    image: nginx:latest
    restart: always
    depends_on:
      - graphql-engine
    volumes:
      - ./nginx_templates:/etc/nginx/templates
      - ${NGINX_LOG_DIR:?}:/logs
    environment:
      - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.nginx

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel run
    restart: always
    depends_on:
      - nginx
    environment:
      TUNNEL_TOKEN: ${CLOUDFLARED_TUNNEL_TOKEN:?}
